### ISSUE TITLE
Node synced waiting for peers - Discovered new validators count=0

### ISSUE THREAD

**Issue by avenbreaks** [q9f/mergednet#3]
i followed as in the dev.to documentation and tried to change the timestap chainId and etc. after i run geth 1 and 2 they are connected fine, after that i run lodestar and 2 nodes are connected but after i run validator it doesn't work, 

`Node is syncing - Service Unavailable - Error on getProposerDuites`

it is very helpful if you can see where my configuration and errors are and I will fix it

**My Configuration :** 
https://txt.mariomichel.com/?67732e6977ed84f6#6WDURqS8asJA4zC4ZfVRq2tnAF67rqzYWck99mJw7j2f

**Config.yaml :** 
https://txt.mariomichel.com/?5083c6349a4425d6#mmvPUKSiQfgKD7wBWgccpkzX2SdjHgfcNyY8TbYSYPk

**Step By Step im copy in here :** 
https://txt.mariomichel.com/?0875899f51a38046#7KsVypNxLDahn3NyagVjMcSrCsovgpSXeqCbanPu2bPa

**Log GETH Node 0 :** 
https://txt.mariomichel.com/?d5bfe7629c6318bb#FafF2Zh8n6jUtk8dCwDsLNf1rV6sUKAqdv2eFwbKEHEF
**Log GETH Node 1 :** 
https://txt.mariomichel.com/?522181afbf140674#Aecbr4m4mokfykWXVC1rcj3VgzbVYXWNGd3XB2pS3YGD
**Beacon Node 0 :** 
https://txt.mariomichel.com/?5e9aae922b976e59#9JyyKdRKbddx7oHGBitRRS2B7eDQxYQvBafx6aEMoioZ
**Beacon Node 1 :** 
https://txt.mariomichel.com/?cf4cc4c91b38fd6d#DjwuWvtyQk7Wk4xgq9c6GQVqqfp7snwWUEL5nEKPzZEN
**Validator** 
https://txt.mariomichel.com/?a88364fa48b1198f#7Fag7bxp2eDHmgY4JW31SQdMFr8fuyQxARxG77tU3WzC

**Logs :** 
```
Jan-08 09:09:00.013[]                 info: Node is syncing - Service Unavailable: Node is syncing - waiting for peers - Error on getProposerDuties
Jan-08 09:09:12.016[]                 info: Node is syncing - Service Unavailable: Node is syncing - waiting for peers - Error on getProposerDuties
Jan-08 09:09:24.007[]                 info: Node is syncing - Service Unavailable: Node is syncing - waiting for peers - Error on getProposerDuties
Jan-08 09:09:36.017[]                 info: Node is syncing - Service Unavailable: Node is syncing - waiting for peers - Error on getProposerDuties
Jan-08 09:09:48.016[]                 info: Node is syncing - Service Unavailable: Node is syncing - waiting for peers - Error on getProposerDuties
```

**Comment by john-risk-adigium** [comment]
I created a [script to automate the process](https://github.com/oone-world/mergednet/blob/a312e82e8407cd1bf390dc997cfa0b8f7bdb1dd7/restart.sh). Maybe you can try it.
Just get the forked repository and run the script

**Comment by avenbreaks** [comment]
> 

can i change the chainId or anything sir ?

**Comment by john-risk-adigium** [comment]
I would suggest trying as is first. 
If it worked, then you can start changing what you want.

**Comment by avenbreaks** [comment]
> I would suggest trying as is first. If it worked, then you can start changing what you want.

node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module '/root/building/lodestar/packages/cli/bin/lodestar.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.13.0

**Comment by john-risk-adigium** [comment]
Did you install lodestar? how?
I compiled it in the following folder /root/building/lodestar.
If you compiled it in another folder, just change the path in clients/lodestar
If you have its executable, from somewhere, replace clients/lodestar with your executable, or make clients/lodestar a symlink to your executable.

**Comment by avenbreaks** [comment]
solved! 
but, i see some error in beacon node : 

Beacon Logs : 
```
PublishError.InsufficientPeers
at Object.submitPoolSyncCommitteeSignatures (file:///workspace/mergednet/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:205:15)
at Object.handler (file:///workspace/mergednet/lodestar/packages/api/src/utils/server/genericJsonServer.ts:41:23)
```

```
Error: Multiple errors on publishContributionAndProofs
PublishError.Duplicate 
at Eth2Gossipsub.publish (file:///workspace/mergednet/lodestar/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:1950:13)
```
for GETH its perfectly running: 

```
INFO [01-09|12:18:05.049] Chain head was updated                   number=14 hash=8b41ba..163480 root=6ef316..55fa86 elapsed="71.81µs"
INFO [01-09|12:18:08.260] Looking for peers                        peercount=1 tried=0 static=0
```

@john-risk-adigium

**Comment by john-risk-adigium** [comment]
You can ignore these errors as per @q9f comment [here](https://github.com/q9f/mergednet/issues/1#issuecomment-1368458316)

**Comment by john-risk-adigium** [comment]
@avenbreaks if you feel your issue is solved please tell us what was the problem and close the issue

**Comment by avenbreaks** [comment]
> You can ignore these errors as per @q9f comment [here](https://github.com/q9f/mergednet/issues/1#issuecomment-1368458316)

okay i can try again sir.

**Comment by avenbreaks** [comment]
> @avenbreaksjika Anda merasa masalah Anda terpecahkan, beri tahu kami apa masalahnya dan tutup masalahnya

@john-risk-adigium 

solved sir, im to ignore this notice
Error: Internal Server Error: PublishError.Duplicate
GETH & Lodestar running perfectly 

hello sir, can I change the config.yaml file before executing?

**Comment by avenbreaks** [comment]
can i add new validator or geth node for sync ? @john-risk-adigium
